Allow overriding Button case
hemilabs/pure.finance pull request #34
Opened 2024-04-29 20:28 UTC by gabmontes

## Summary

If a case is specified for the `Button` component, override the default `capitalize` class.

## Screenshots

<img width="423" alt="image" src="https://github.com/hemilabs/pure.finance/assets/2621975/325e4aa4-0630-4a5b-9def-89bd1baaf6db">

2024-04-30 19:33 UTC, leanazulyoro requested changes

2024-04-30 19:33 UTC, leanazulyoro commented on site/components/Button.js
> +  const textStyle = `text-center text-base text-white ${textCase}`
I don't really like this, could we consider using tailwind merge? if not now, let's create an issue to do so.

2024-05-02 13:58 UTC, leanazulyoro approved these changes

2024-05-02 14:46 UTC, gndelia approved these changes

2024-05-02 14:46 UTC, merged